import { InsomniaTechnique } from '../common/types/entities';

export const INSOMNIA_RISK_FACTORS = [
  'Psychological stress',
  'Chronic pain',
  'Cardiovascular anxiety',
  'Hyperthyroidism',
  'Restless legs syndrome',
  'Menopause',
  'Medication effects',
  'Caffeine',
  'Nicotine',
  'Alcohol',
  'Depression (HPA-axis dysregulation)',
  'Nocturia',
  'Psychoactive substances',
  'Thoracic surgery history',
  'Nasal septum deviation',
  'Hormonal fluctuations',
  'Life stress events',
  'GI issues',
  'Psychiatric disorders',
  'Neurological disorders',
  'Poor sleep hygiene',
  'Athlete overtraining insomnia',
  'Fatal familial insomnia (educational only)',
  'Circadian rhythm disorder',
  'Age-related hormonal shifts',
];

export const TECHNIQUE_LIBRARY: InsomniaTechnique[] = [
  { name: 'Cognitive shuffle', category: 'cognitive', tags: ['thought defusion'], contraindications: [], instructionText: 'Pick a neutral word and imagine unrelated objects for each letter until sleepiness rises.', duration: '10-20 min', recommendedFor: ['sleep-onset'], avoidanceConditions: ['active psychosis'] },
  { name: 'Image carousel', category: 'cognitive', tags: ['imagery'], contraindications: [], instructionText: 'Cycle calm mental snapshots every 5-10 seconds without storyline.', duration: '10 min', recommendedFor: ['sleep-onset'], avoidanceConditions: [] },
  { name: 'Worry container journaling', category: 'cognitive', tags: ['journaling'], contraindications: [], instructionText: 'Write worries, park them in a planned worry window for tomorrow.', duration: '15 min', recommendedFor: ['anxiety'], avoidanceConditions: [] },
  { name: 'Paradoxical procrastination', category: 'cognitive', tags: ['paradoxical intention'], contraindications: [], instructionText: 'Gently try to stay awake while resting still; remove pressure to sleep.', duration: '15 min', recommendedFor: ['performance anxiety'], avoidanceConditions: ['mania'] },
  { name: 'Rule of 15 minutes', category: 'cognitive', tags: ['stimulus control'], contraindications: [], instructionText: 'If awake and frustrated, leave bed for calm low-light activity; return when sleepy.', duration: 'as needed', recommendedFor: ['maintenance'], avoidanceConditions: [] },
  { name: 'Zero thought meditation', category: 'cognitive', tags: ['meditation'], contraindications: [], instructionText: 'Observe thoughts as passing events and return attention to breath.', duration: '10 min', recommendedFor: ['rumination'], avoidanceConditions: [] },
  { name: 'Reverse day review', category: 'cognitive', tags: ['attention training'], contraindications: [], instructionText: 'Replay day backwards in factual, non-emotional detail.', duration: '10 min', recommendedFor: ['mind racing'], avoidanceConditions: [] },
  { name: 'Progressive muscle relaxation (Jacobson)', category: 'somatic', tags: ['pmr'], contraindications: ['acute muscular injury'], instructionText: 'Tense and release each muscle group from feet to face.', duration: '12 min', recommendedFor: ['somatic tension'], avoidanceConditions: [] },
  { name: 'Body scan', category: 'somatic', tags: ['interoception'], contraindications: [], instructionText: 'Move attention body-part by body-part, relaxing on exhale.', duration: '10-20 min', recommendedFor: ['hyperarousal'], avoidanceConditions: [] },
  { name: 'Autogenic training', category: 'somatic', tags: ['self-suggestion'], contraindications: [], instructionText: 'Repeat warmth and heaviness phrases while breathing slowly.', duration: '10 min', recommendedFor: ['anxiety'], avoidanceConditions: [] },
  { name: 'Foot warming protocol', category: 'somatic', tags: ['thermoregulation'], contraindications: ['neuropathy'], instructionText: 'Use warm socks or bath to induce distal vasodilation before bed.', duration: '20 min', recommendedFor: ['sleep-onset'], avoidanceConditions: ['heat intolerance'] },
  { name: 'Ear self-massage', category: 'somatic', tags: ['vagal soothing'], contraindications: [], instructionText: 'Massage outer ear and lobes with slow bilateral circles.', duration: '5 min', recommendedFor: ['pre-sleep calm'], avoidanceConditions: [] },
  { name: 'Corpse pose (Shavasana)', category: 'somatic', tags: ['rest posture'], contraindications: [], instructionText: 'Lie supine with palms up, soften jaw and abdomen.', duration: '10 min', recommendedFor: ['body tension'], avoidanceConditions: ['severe back pain'] },
  { name: 'Ankle rotation', category: 'somatic', tags: ['gentle mobility'], contraindications: ['acute sprain'], instructionText: 'Rotate ankles slowly 10 reps each direction per side.', duration: '3 min', recommendedFor: ['restless body'], avoidanceConditions: [] },
  { name: 'Supine spinal twist', category: 'somatic', tags: ['mobility'], contraindications: ['recent spine surgery'], instructionText: 'Knees to one side while shoulders grounded; breathe deeply.', duration: '4 min', recommendedFor: ['somatic wind-down'], avoidanceConditions: ['pregnancy discomfort'] },
  { name: 'Acupressure (Yin-tang, He-gu)', category: 'somatic', tags: ['acupressure'], contraindications: ['pregnancy caution for He-gu'], instructionText: 'Apply gentle pressure 30-60 seconds each point.', duration: '5 min', recommendedFor: ['pre-sleep anxiety'], avoidanceConditions: [] },
  { name: '4-7-8 breathing', category: 'breathing', tags: ['paced breathing'], contraindications: ['severe COPD'], instructionText: 'Inhale 4, hold 7, exhale 8 for 4 cycles.', duration: '3-5 min', recommendedFor: ['sleep onset'], avoidanceConditions: ['dizziness'] },
  { name: 'Diaphragmatic breathing', category: 'breathing', tags: ['diaphragm'], contraindications: [], instructionText: 'Belly rises on inhale, falls on prolonged exhale.', duration: '10 min', recommendedFor: ['hyperarousal'], avoidanceConditions: [] },
  { name: 'Extended exhale breathing', category: 'breathing', tags: ['parasympathetic'], contraindications: [], instructionText: 'Use 4-second inhale with 6-8 second exhale.', duration: '5-10 min', recommendedFor: ['anxiety'], avoidanceConditions: [] },
  { name: 'Left nostril breathing', category: 'breathing', tags: ['yogic'], contraindications: ['nasal obstruction'], instructionText: 'Close right nostril, breathe calmly via left.', duration: '5 min', recommendedFor: ['down-regulation'], avoidanceConditions: [] },
  { name: 'Breath counting', category: 'breathing', tags: ['mindfulness'], contraindications: [], instructionText: 'Count breaths 1 to 10 repeatedly, reset when distracted.', duration: '10 min', recommendedFor: ['mind wandering'], avoidanceConditions: [] },
  { name: 'Candle visualization breathing', category: 'breathing', tags: ['visual focus'], contraindications: [], instructionText: 'Imagine exhale gently moving candle flame without extinguishing.', duration: '6 min', recommendedFor: ['mental settling'], avoidanceConditions: [] },
  { name: 'Safe place imagery', category: 'visualization', tags: ['imagery'], contraindications: [], instructionText: 'Create detailed multisensory safe place scene.', duration: '8 min', recommendedFor: ['night anxiety'], avoidanceConditions: [] },
  { name: 'Elevator descent', category: 'visualization', tags: ['descent'], contraindications: [], instructionText: 'Imagine descending floors with each exhale.', duration: '5 min', recommendedFor: ['sleep onset'], avoidanceConditions: ['claustrophobia'] },
  { name: 'Snow screen', category: 'visualization', tags: ['neutral imagery'], contraindications: [], instructionText: 'Picture old-TV static, neutral and repetitive.', duration: '5 min', recommendedFor: ['intrusive thoughts'], avoidanceConditions: [] },
  { name: 'Stone at bottom of river', category: 'visualization', tags: ['grounding'], contraindications: [], instructionText: 'Visualize being stable stone while water-thoughts flow above.', duration: '6 min', recommendedFor: ['cognitive arousal'], avoidanceConditions: [] },
  { name: 'Lake boat imagery', category: 'visualization', tags: ['rhythm'], contraindications: [], instructionText: 'Imagine gentle boat rocking synchronized with breath.', duration: '8 min', recommendedFor: ['somatic restlessness'], avoidanceConditions: [] },
  { name: 'White noise waterfall', category: 'visualization', tags: ['masking'], contraindications: [], instructionText: 'Imagine waterfall masking intrusive sounds and thoughts.', duration: '6 min', recommendedFor: ['environmental sensitivity'], avoidanceConditions: [] },
  { name: 'Wake anchor', category: 'behavioral', tags: ['cbt-i'], contraindications: [], instructionText: 'Keep fixed wake time every day including weekends.', duration: 'daily', recommendedFor: ['all'], avoidanceConditions: [] },
  { name: '30-minute ritual', category: 'behavioral', tags: ['routine'], contraindications: [], instructionText: 'Low-light, low-stimulation wind-down routine each night.', duration: '30 min', recommendedFor: ['all'], avoidanceConditions: [] },
  { name: 'Screen removal', category: 'behavioral', tags: ['hygiene'], contraindications: [], instructionText: 'Avoid bright screens 60-90 min before bed.', duration: 'nightly', recommendedFor: ['sleep onset'], avoidanceConditions: [] },
  { name: 'Bed-only-for-sleep rule', category: 'behavioral', tags: ['stimulus control'], contraindications: [], instructionText: 'Use bed only for sleep and intimacy.', duration: 'ongoing', recommendedFor: ['conditioned arousal'], avoidanceConditions: [] },
  { name: 'Temperature reduction 18–20°C', category: 'behavioral', tags: ['environment'], contraindications: [], instructionText: 'Target cool bedroom environment around 18-20°C.', duration: 'nightly', recommendedFor: ['maintenance'], avoidanceConditions: ['cold intolerance'] },
  { name: 'Anti-clock viewing', category: 'behavioral', tags: ['anti-pattern'], contraindications: [], instructionText: 'Turn clocks away and disable visible time checks overnight.', duration: 'nightly', recommendedFor: ['catastrophizing'], avoidanceConditions: [] },
  { name: 'Daylight exposure', category: 'behavioral', tags: ['circadian'], contraindications: [], instructionText: 'Get 10-30 minutes outdoor light in early morning.', duration: 'daily', recommendedFor: ['circadian delay'], avoidanceConditions: [] },
  { name: 'No daytime oversleeping', category: 'behavioral', tags: ['sleep pressure'], contraindications: [], instructionText: 'Avoid long daytime sleeping and keep naps brief if needed.', duration: 'daily', recommendedFor: ['fragmentation'], avoidanceConditions: [] },
  { name: 'Avoid heavy meals before sleep', category: 'nutrition', tags: ['nutrition'], contraindications: [], instructionText: 'Finish heavy meals at least 2-3 hours before bedtime.', duration: 'daily', recommendedFor: ['GI-triggered insomnia'], avoidanceConditions: [] },
  { name: 'Dinner ≤20% daily calories', category: 'nutrition', tags: ['nutrition'], contraindications: [], instructionText: 'Prefer lighter dinner to reduce nocturnal metabolic load.', duration: 'daily', recommendedFor: ['maintenance'], avoidanceConditions: [] },
  { name: 'Reduce caffeine 6–8h before sleep', category: 'nutrition', tags: ['caffeine'], contraindications: [], instructionText: 'Set last caffeine cutoff at least 6-8 hours pre-bed.', duration: 'daily', recommendedFor: ['sleep onset'], avoidanceConditions: [] },
  { name: 'Encourage 500g fruits/vegetables daily', category: 'nutrition', tags: ['nutrition'], contraindications: [], instructionText: 'Support balanced daytime intake with 500g produce goal.', duration: 'daily', recommendedFor: ['general health'], avoidanceConditions: [] },
  { name: 'Magnesium/B-vitamin education (no supplementation dosing)', category: 'nutrition', tags: ['education'], contraindications: [], instructionText: 'Educate on food sources; no dosing instructions provided.', duration: 'educational', recommendedFor: ['education'], avoidanceConditions: [] },
  { name: 'Going to bed earlier to compensate', category: 'anti-pattern', tags: ['sleep pressure'], contraindications: [], instructionText: 'Avoid compensation bedtime drift; maintain prescribed window.', duration: 'monitor', recommendedFor: ['relapse prevention'], avoidanceConditions: [] },
  { name: 'Sleeping late to recover', category: 'anti-pattern', tags: ['circadian drift'], contraindications: [], instructionText: 'Keep wake anchor despite poor nights to protect rhythm.', duration: 'monitor', recommendedFor: ['relapse prevention'], avoidanceConditions: [] },
  { name: 'Staying in bed >9h', category: 'anti-pattern', tags: ['efficiency'], contraindications: [], instructionText: 'Limit time in bed to improve homeostatic drive.', duration: 'monitor', recommendedFor: ['low SE'], avoidanceConditions: [] },
  { name: 'Doom-scrolling at 3am', category: 'anti-pattern', tags: ['screen'], contraindications: [], instructionText: 'Replace overnight scrolling with low-light neutral activity.', duration: 'monitor', recommendedFor: ['maintenance insomnia'], avoidanceConditions: [] },
  { name: 'Catastrophic thinking', category: 'anti-pattern', tags: ['cbt'], contraindications: [], instructionText: 'Use evidence-based reframe and probability balancing.', duration: 'monitor', recommendedFor: ['cognitive arousal'], avoidanceConditions: [] },
  { name: 'Clock checking', category: 'anti-pattern', tags: ['arousal'], contraindications: [], instructionText: 'Hide time cues overnight to reduce threat monitoring.', duration: 'monitor', recommendedFor: ['sleep anxiety'], avoidanceConditions: [] },
];

export const EDUCATION_TOPICS = [
  'Hyperarousal explanation',
  'HPA-axis and cortisol',
  'Why sleep restriction works',
  'Circadian rhythm education',
  'Temperature physiology',
  'Why alcohol disrupts REM',
  'Why caffeine blocks adenosine',
  'Why clock-checking worsens insomnia',
];
